_format_version: "2.1"
_transform: true

services:

  #sistema de bibliote virtual
  - name: ApiBibliotecaPortalWeb
    url: http://apibibliotecaportalweb:7778
    connect_timeout: 300000
    read_timeout: 300000
    write_timeout: 300000
    retries: 5
    routes:
      - name: ApiBibPortal_route
        paths:
          - /api-bibportal
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        strip_path: true
        preserve_host: false

  - name: FrontendAngularPortalWeb
    url: http://angularportalweb:4195
    routes:
      - name: FrontendAngularPortalWeb_route
        paths:
          - /
        methods:
          - GET
        strip_path: false
        preserve_host: false